# Generated by Django 2.0.3 on 2018-04-05 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180331_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='programm name')),
                ('is_default', models.BinaryField(default=False)),
                ('is_active', models.BinaryField(default=True)),
                ('description', models.TextField(blank=True, verbose_name='what is this programm for')),
                ('completed_tasks', models.IntegerField(blank=True, null=True)),
                ('spent_time', models.IntegerField(blank=True, null=True)),
                ('last_activity', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'programm',
                'verbose_name_plural': 'programms',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.RemoveField(
            model_name='programm',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-last_activity'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='lazy_days',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lazy_days',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BinaryField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BinaryField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 15, 21, 24, 514803)),
        ),
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 15, 21, 24, 513480)),
        ),
        migrations.AddField(
            model_name='profile',
            name='register_from',
            field=models.CharField(default='telegram', max_length=200, verbose_name='register from'),
        ),
        migrations.AddField(
            model_name='profile',
            name='register_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='programm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
        migrations.DeleteModel(
            name='Programm',
        ),
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
