# Generated by Django 2.0.3 on 2018-04-05 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180405_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 15, 32, 52, 709623)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 15, 32, 52, 708379)),
        ),
    ]
