# Generated by Django 2.0.3 on 2018-04-05 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180405_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 15, 36, 0, 135116)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 5, 15, 36, 0, 133923)),
        ),
    ]
