# Generated by Django 2.0.3 on 2018-04-17 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 16, 7, 10, 250278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 16, 7, 10, 250960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 16, 7, 10, 249568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 16, 7, 10, 251608, tzinfo=utc)),
        ),
    ]
