# Generated by Django 2.0.3 on 2018-07-22 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180425_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 19, 35, 3, 554576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 19, 35, 3, 554576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 19, 35, 3, 554576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 19, 35, 3, 554576, tzinfo=utc)),
        ),
    ]
