# Generated by Django 2.0.3 on 2018-07-29 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180722_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 7, 29, 6, 50, 20, 898766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 7, 29, 6, 50, 20, 898766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 7, 29, 6, 50, 20, 898766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 7, 29, 6, 50, 20, 898766, tzinfo=utc)),
        ),
    ]
