# Generated by Django 2.0.3 on 2018-09-01 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180729_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 6, 50, 6, 914972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 6, 50, 6, 914972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 6, 50, 6, 914972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 6, 50, 6, 914972, tzinfo=utc)),
        ),
    ]
