# Generated by Django 2.0.3 on 2018-03-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messager', models.CharField(max_length=200)),
                ('url_prefix', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('message_type', models.IntegerField(choices=[(0, 'greeting'), (1, 'approval'), (2, 'failure'), (3, 'chatter')], default=3)),
            ],
        ),
    ]
