# Generated by Django 2.0.3 on 2018-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytarget',
            name='is_auto_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouptarget',
            name='is_auto_default',
            field=models.BooleanField(default=False),
        ),
    ]
