# Generated by Django 2.0.3 on 2018-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lang',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
