# Generated by Django 2.0.3 on 2018-04-18 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180417_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 16, 55, 40, 295735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 16, 55, 40, 296363, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 16, 55, 40, 295060, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 16, 55, 40, 297039, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'group')},
        ),
    ]
